title: Himanshu Chouhan
description: Sharing insights on AI, technology, and innovation
baseurl: ""
url: "https://himanshuchouhan.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Personal info
author:
  name: Himanshu Chouhan
  email: your.email@example.com  # Replace with your email

# Navigation
header_pages:
  - about.md
  - posts.md

# Show excerpts on home page
show_excerpts: true

# Minima theme settings
minima:
  social_links:
    linkedin: himanshuchouhan  # Replace with your LinkedIn username
    github: himanshuchouhan
