title: Your Name
description: Your tagline or description
baseurl: ""
url: "https://yourusername.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Personal info
author:
  name: Your Name
  email: your.email@example.com
  linkedin: your-linkedin-profile
